#!/usr/bin/env bun
/**
 * Build an installable plugin bundle for a host whose `packaging` is 'plugin'.
 *
 * WHY THIS EXISTS. Before it, the Cowork build of Boots was a hand-made snapshot
 * that lived nowhere in the repo. It drifted in BOTH directions within a week —
 * it was missing a skill the repo had, and it was ahead of the repo on a router
 * bullet and nine translation-table rows — and nobody noticed either way, because
 * there was nothing to diff it against. This script makes the repo the only
 * source: `bun run build:cowork` and the bundle is whatever the templates say.
 *
 * WHAT IT PRODUCES
 *
 *   dist/<host>/
 *   ├── .claude-plugin/plugin.json   the manifest the host reads
 *   ├── VERSION                       so an installed copy can be compared
 *   ├── README.md                     what the user sees in the marketplace
 *   └── skills/
 *       ├── boots/
 *       │   ├── SKILL.md              generated by gen-skill-docs --host <host>
 *       │   ├── bin/                  the runtime scripts, copied whole
 *       │   ├── forms/                every palette (a system may name any of them)
 *       │   ├── reference/            the home protocol and friends
 *       │   └── examples/
 *       └── boots-<stage>/SKILL.md      one dir per stage skill
 *
 * The SKILL.md files are already in place when this runs — gen-skill-docs writes
 * them straight into dist/<host>/skills/. This script adds the manifest and the
 * bundled resources that travel with the `boots` skill, and then checks the
 * result is actually loadable rather than merely present.
 *
 * Usage:
 *   bun run scripts/build-plugin.ts --host cowork
 *   bun run scripts/build-plugin.ts --host cowork --check   # verify, don't write
 */

import * as fs from 'fs';
import * as path from 'path';
import { getHostConfig, resolveHostArg } from '../hosts/index';
import { validateHostConfig, paletteFileFor } from './host-config';

const ROOT = path.resolve(import.meta.dir, '..');

// ─── Args ────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const CHECK_ONLY = argv.includes('--check');
const hostArgIdx = argv.findIndex(a => a === '--host' || a.startsWith('--host='));
const hostRaw = hostArgIdx === -1
  ? 'cowork'
  : (argv[hostArgIdx].includes('=') ? argv[hostArgIdx].split('=')[1] : argv[hostArgIdx + 1]);
const HOST = resolveHostArg(hostRaw);
const hostConfig = getHostConfig(HOST);

// ─── Guards ──────────────────────────────────────────────────
const configErrors = validateHostConfig(hostConfig);
if (configErrors.length) {
  console.error(`hosts/${HOST}.ts is invalid:\n  ${configErrors.join('\n  ')}`);
  process.exit(1);
}
if (hostConfig.packaging !== 'plugin') {
  console.error(
    `host '${HOST}' has packaging '${hostConfig.packaging ?? 'symlink'}', not 'plugin'.\n` +
    `Symlink hosts install with ./setup — there is no bundle to build.`,
  );
  process.exit(1);
}

// A host that names a palette the repo does not ship would generate skills that
// tell the agent to read a file that isn't there — at run time, in a real
// session, silently. Fail the build instead.
const palette = paletteFileFor(hostConfig);
if (!fs.existsSync(path.join(ROOT, palette))) {
  console.error(`host '${HOST}' names palette '${hostConfig.platform.palette}' but ${palette} does not exist.`);
  process.exit(1);
}

const OUT = path.join(ROOT, hostConfig.hostSubdir);
const SKILLS_OUT = path.join(OUT, 'skills');

// ─── Preflight: the generator must have run first ────────────
if (!fs.existsSync(path.join(SKILLS_OUT, 'boots', 'SKILL.md'))) {
  console.error(
    `no generated skills at ${path.relative(ROOT, SKILLS_OUT)}.\n` +
    `Run: bun run gen:skill-docs --host ${HOST}`,
  );
  process.exit(1);
}

// ─── Resources that travel with the `boots` skill ────────────
// These are read at RUN TIME by the skills (the palette, the home protocol, the
// first-run example, the bin scripts), so they have to be inside the bundle. A
// skill that points at a path outside the plugin is a skill that breaks the
// moment it is installed anywhere but this machine.
const BUNDLED = ['bin', 'forms', 'reference', 'examples'];

function copyDir(src: string, dest: string) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else {
      fs.copyFileSync(s, d);
      // Preserve the executable bit — the bin scripts are useless without it,
      // and the failure is a confusing "permission denied" at run time.
      const mode = fs.statSync(s).mode;
      if (mode & 0o111) fs.chmodSync(d, mode);
    }
  }
}

const written: string[] = [];

if (!CHECK_ONLY) {
  // 1. Bundled resources next to the boots SKILL.md.
  for (const dir of BUNDLED) {
    const src = path.join(ROOT, 'boots', dir);
    if (!fs.existsSync(src)) continue;
    const dest = path.join(SKILLS_OUT, 'boots', dir);
    copyDir(src, dest);

    // Everything in bin/ is an executable by definition, and the bit is easy to
    // lose in transit — a git checkout with the wrong core.fileMode, a file moved
    // across the device bridge, a zip round-trip. The failure it causes at run
    // time is a bare "permission denied" that reads like a bug in Boots. So set
    // it here rather than depending on what the working tree happens to have.
    if (dir === 'bin') {
      for (const f of fs.readdirSync(dest)) {
        if (f.startsWith('.')) continue;
        fs.chmodSync(path.join(dest, f), 0o755);
      }
    }
    written.push(`skills/boots/${dir}/`);
  }

  // 2. The manifest. Description and keywords are the marketplace's copy, so they
  //    are written for a person browsing, not for the agent.
  //
  //    THE MANIFEST DELIBERATELY CARRIES NO `version`, AND THAT IS THE WHOLE
  //    UPDATE MECHANISM. Claude Code resolves a plugin's version from the first
  //    of: plugin.json `version` → the marketplace entry's `version` → the git
  //    commit SHA of the source. A version string PINS the plugin: an installed
  //    copy compares the resolved version against its own and, when they match,
  //    `/plugin update` and the background auto-update both skip it and report
  //    "already at the latest version". So writing `0.1.0` here would mean every
  //    fix pushed after a user's first install is invisible to them until
  //    somebody remembers to bump VERSION.
  //
  //    That failure has already happened to this project once, in a different
  //    costume: a Cowork user ran a months-stale hand-made snapshot for a whole
  //    session because nothing made staleness visible. Omitting `version` makes
  //    every commit a new version, so `git push` IS the release and users cannot
  //    silently fall behind. Do not add it back without replacing it with a
  //    release process that bumps VERSION on every user-visible change.
  //
  //    VERSION still ships in the bundle (step 3) so an installed copy can say
  //    which release it came from — it just isn't the update key.
  const rawVersion = fs.readFileSync(path.join(ROOT, 'VERSION'), 'utf-8').trim();
  const manifest = {
    name: 'boots',
    description:
      `A companion for building and finishing AI systems in ${hostConfig.platform.runtime}. ` +
      `Holds a model of every system you have in flight, always has the one next step, ` +
      `and closes what you start.`,
    author: { name: 'Fourday AI' },
    keywords: ['systems', 'building', 'pipeline', 'coach', 'continuity'],
  };
  fs.mkdirSync(path.join(OUT, '.claude-plugin'), { recursive: true });
  fs.writeFileSync(
    path.join(OUT, '.claude-plugin', 'plugin.json'),
    JSON.stringify(manifest, null, 2) + '\n',
  );
  written.push('.claude-plugin/plugin.json');

  // 3. VERSION, so an installed copy can tell itself apart from a published one.
  //    Informational only — see the note above on why it is not the update key.
  fs.writeFileSync(path.join(OUT, 'VERSION'), rawVersion + '\n');
  written.push('VERSION');

  // 4. README, if the repo has one worth shipping.
  const readme = path.join(ROOT, 'README.md');
  if (fs.existsSync(readme)) {
    fs.copyFileSync(readme, path.join(OUT, 'README.md'));
    written.push('README.md');
  }
}

// ─── Verify the bundle is loadable, not merely present ───────
// "The files exist" is the check that passes falsely. These are the things that
// would actually break in a real session.
const problems: string[] = [];

const manifestPath = path.join(OUT, '.claude-plugin', 'plugin.json');
if (!fs.existsSync(manifestPath)) problems.push('missing .claude-plugin/plugin.json');
else {
  try {
    const m = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
    if (!m.name) problems.push('plugin.json has no name');
    // The INVERSE of the usual check, on purpose. A `version` here pins the
    // plugin and silently stops users receiving updates — see the manifest note
    // above. Absence is the correct state; presence is the bug.
    if (m.version) {
      problems.push(
        `plugin.json declares version '${m.version}' — this pins the plugin and ` +
        `stops installed copies receiving updates. Omit it so the commit SHA is the version.`,
      );
    }
  } catch (e) {
    problems.push(`plugin.json is not valid JSON: ${e}`);
  }
}

const skillDirs = fs.existsSync(SKILLS_OUT)
  ? fs.readdirSync(SKILLS_OUT, { withFileTypes: true }).filter(d => d.isDirectory()).map(d => d.name)
  : [];

// Every skill the host did not deliberately skip must be here. A silently
// missing skill is exactly how the hand-made snapshot lost boots-upgrade.
const expected = fs.readdirSync(ROOT, { withFileTypes: true })
  .filter(d => d.isDirectory() && /^boots(-|$)/.test(d.name))
  .filter(d => fs.existsSync(path.join(ROOT, d.name, 'SKILL.md.tmpl')))
  .map(d => d.name)
  .filter(n => !(hostConfig.generation.skipSkills || []).includes(n));

for (const name of expected) {
  if (!skillDirs.includes(name)) problems.push(`skill '${name}' is missing from the bundle`);
}
for (const name of skillDirs) {
  const sk = path.join(SKILLS_OUT, name, 'SKILL.md');
  if (!fs.existsSync(sk)) { problems.push(`${name}/ has no SKILL.md`); continue; }
  const body = fs.readFileSync(sk, 'utf-8');
  if (!body.startsWith('---')) problems.push(`${name}/SKILL.md has no frontmatter`);
  if (!/^name:\s*\S/m.test(body)) problems.push(`${name}/SKILL.md has no name: field`);
  // An unresolved placeholder reaching a user's session is a silent instruction
  // to read a path that does not exist.
  const stray = body.match(/\{\{[A-Z_]+(?::[^}]+)?\}\}/g);
  if (stray) problems.push(`${name}/SKILL.md has unresolved placeholders: ${[...new Set(stray)].join(', ')}`);
  // The whole point of a plugin build: nothing may point at the author's machine.
  if (body.includes('/Users/') || body.includes('/home/claude/')) {
    problems.push(`${name}/SKILL.md contains an absolute path from the build machine`);
  }
}

// The bundled resources the skills read at run time.
for (const dir of BUNDLED) {
  const src = path.join(ROOT, 'boots', dir);
  if (!fs.existsSync(src)) continue;
  if (!fs.existsSync(path.join(SKILLS_OUT, 'boots', dir))) {
    problems.push(`skills/boots/${dir}/ is missing — the skills read it at run time`);
  }
}
const palettePath = path.join(SKILLS_OUT, 'boots', 'forms', `${hostConfig.platform.palette}.md`);
if (!fs.existsSync(palettePath)) {
  problems.push(`the default palette ${hostConfig.platform.palette}.md is not in the bundle`);
}
const homeScript = path.join(SKILLS_OUT, 'boots', 'bin', 'boots-home');
if (hostConfig.platform.homeModel === 'resolved') {
  if (!fs.existsSync(homeScript)) {
    problems.push(`homeModel is 'resolved' but bin/boots-home is not in the bundle`);
  } else if (!(fs.statSync(homeScript).mode & 0o111)) {
    problems.push(`bin/boots-home is not executable`);
  }
}

// ─── Report ──────────────────────────────────────────────────
if (!CHECK_ONLY) {
  for (const w of written) console.log(`BUNDLED: ${w}`);
  console.log(`BUNDLED: skills/ (${skillDirs.length} skills)`);
}

if (problems.length) {
  console.error(`\n${problems.length} problem(s) with the ${HOST} bundle:`);
  for (const p of problems) console.error(`  ✗ ${p}`);
  process.exit(1);
}

console.log(
  `\nOK — ${path.relative(ROOT, OUT)} is a loadable ${hostConfig.displayName} plugin ` +
  `(${skillDirs.length} skills, palette '${hostConfig.platform.palette}', home '${hostConfig.platform.homeModel}').`,
);
